# EDA

## Exploratory Data Analysis
for patterns and structures

- load and structure
- clean data
- statistical summary
- visualization

In [4]:
import pandas as pd

In [7]:
info = {
    "Name" : ["Sashwat", "Harshita", "Shradha"] ,
    "CGPA" : [9.5, 7.5, 8.5]
}

df = pd.DataFrame(info)
print(df)

       Name  CGPA
0   Sashwat   9.5
1  Harshita   7.5
2   Shradha   8.5

In [8]:
df

       Name  CGPA
0   Sashwat   9.5
1  Harshita   7.5
2   Shradha   8.5

# Series

In [13]:
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))


#index
print(s[0])
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
3

## important
index means position , and label means , named index

In [19]:
s = pd.Series([23, 45,  67, 34], index = ["Adam", "Eve", "Bob", "Bean"])
print(s)

#excessing labelled based 
print(s["Adam"])

print(s.index)

Adam    23
Eve     45
Bob     67
Bean    34
dtype: int64
23
Index(['Adam', 'Eve', 'Bob', 'Bean'], dtype='object')

In [21]:
s

Adam    23
Eve     45
Bob     67
Bean    34
dtype: int64

In [29]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])

print(s1 + s2)

s1[0] = 100
changed_s1 = s1.drop(0)

print(s1)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [27]:
s1

0    100
1      2
2      3
3      4
4      5
dtype: int64

# DataFrame

In [31]:
info = {
    "Name":["Adam", "Eve", "Bon"],
    "Age":[23, 24,  25],
    'GPA': [9.4, 8.6, 7.6]
}

df = pd.DataFrame(info)

In [33]:
df

   Name  Age  GPA
0  Adam   23  9.4
1   Eve   24  8.6
2   Bon   25  7.6

In [35]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [39]:
df = pd.DataFrame([["Adam", 23], ["Eve", 23], ["Bob", 23]], columns = ["name", "Age"])

In [40]:
df

   name  Age
0  Adam   23
1   Eve   23
2   Bob   23

In [41]:
import numpy as np

In [43]:
np_arr = np.array([[1, 2, 3], [4, 5, 6]])

df = pd.DataFrame(np_arr, columns =["A", "B", "C"])

In [44]:
df

   A  B  C
0  1  2  3
1  4  5  6

# Usage with csv and json files

In [45]:
#csv data

In [46]:
df = pd.read_csv("employee_data.csv")

print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [49]:
#json data

df = pd.read_json("employee_data.json")

print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>