# EDA

## Exploratory Data Analysis
for patterns and structures

- load and structure
- clean data
- statistical summary
- visualization

In [1]:
import pandas as pd

In [2]:
info = {
    "Name" : ["Sashwat", "Harshita", "Shradha"] ,
    "CGPA" : [9.5, 7.5, 8.5]
}

df = pd.DataFrame(info)
print(df)

       Name  CGPA
0   Sashwat   9.5
1  Harshita   7.5
2   Shradha   8.5

In [3]:
df

       Name  CGPA
0   Sashwat   9.5
1  Harshita   7.5
2   Shradha   8.5

# Series

In [4]:
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))


#index
print(s[0])
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
3

## important
index means position , and label means , named index

In [5]:
s = pd.Series([23, 45,  67, 34], index = ["Adam", "Eve", "Bob", "Bean"])
print(s)

#excessing labelled based 
print(s["Adam"])

print(s.index)

Adam    23
Eve     45
Bob     67
Bean    34
dtype: int64
23
Index(['Adam', 'Eve', 'Bob', 'Bean'], dtype='object')

In [6]:
s

Adam    23
Eve     45
Bob     67
Bean    34
dtype: int64

In [7]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])

print(s1 + s2)

s1[0] = 100
changed_s1 = s1.drop(0)

print(s1)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
s1

0    100
1      2
2      3
3      4
4      5
dtype: int64

# DataFrame

In [9]:
info = {
    "Name":["Adam", "Eve", "Bon"],
    "Age":[23, 24,  25],
    'GPA': [9.4, 8.6, 7.6]
}

df = pd.DataFrame(info)

In [10]:
df

   Name  Age  GPA
0  Adam   23  9.4
1   Eve   24  8.6
2   Bon   25  7.6

In [11]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [12]:
df = pd.DataFrame([["Adam", 23], ["Eve", 23], ["Bob", 23]], columns = ["name", "Age"])

In [13]:
df

   name  Age
0  Adam   23
1   Eve   23
2   Bob   23

In [14]:
import numpy as np

In [15]:
np_arr = np.array([[1, 2, 3], [4, 5, 6]])

df = pd.DataFrame(np_arr, columns =["A", "B", "C"])

In [16]:
df

   A  B  C
0  1  2  3
1  4  5  6

# Usage with csv and json files

In [17]:
#csv data

In [18]:
df = pd.read_csv("employee_data.csv")

print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [19]:
#json data

df = pd.read_json("employee_data.json")

print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [20]:
#methods

In [21]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [22]:
#methods

df.head() #starting 5 rows
df.tail() #last 5 rows rows
df.sample()  #prints any random row for the sample
df.info()  #summery of data
df.shape  #returns a tuple (row,column)
df.describe()  # describes the data like min , max , mean etc
df.columns  #prints all the column
df.nunique()  #prints  number of unique values in the rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

# AQI Data Set

In [23]:
df = pd.read_csv("globalAirQuality.csv")

In [24]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [25]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [26]:
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [27]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

## selecting the data

In [28]:
#selecting columns
df["city"]
df[["city",  "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

## selecting row

In [29]:

#(label and index based)  loc  and iloc

df.loc[0]
df.loc[0:2] #start index : ending index  (inclusice)

df.iloc[2]  
df.iloc[0:2]  #start index : end index(exclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [30]:
# for rows and columns

#single value
df.loc[0:2 ,["city", "aqi"]]

       city  aqi
0  New York  108
1  New York   90
2  New York   84

In [31]:
df.loc[0:2 ,["country","city","latitude", "longitude"]]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [32]:
df.iloc[0:3 ,1:5]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [33]:
# single scaler value 
# at and iat

df.at[0, "city" ]

'New York'

In [34]:
df.iat[0, 2]

'New York'

## filtering Data

In [35]:
df[ df["aqi"] > 100]

df[ (df["aqi"] > 100) & (df["temperature"] > 30)]
df[ (df["aqi"] > 100) & (df["temperature"] > 30)]

df[ df["aqi"] > 100 ] [["city", "aqi"]]

aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]

aqi_data.iloc[0]

#aqi_data.loc[0]  # this index doesnt exist 
aqi_data.loc[6]

city    New York
aqi          155
Name: 6, dtype: object

## Query Method

In [36]:
# query returns a copy - a view 

df.query("aqi > 100")

df.query("aqi > 100 & temperature > 30") [["city", "aqi"]]

aqi_value = 100
df.query("aqi > @aqi_value & temperature > 30") [["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

# Cleaning Data
## Handle missing Values
- isnull() / isna()
- isnull().sum()
- dropna()
- fillna(value)
- ffill() - forward fill
- bfill() - backward fill

In [37]:
df = pd.read_csv("raw_data.csv")

In [38]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [39]:
df.isnull()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [40]:
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [41]:
df.dropna() #rows drop

df.dropna(axis=1) #columns drop

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [42]:
df.fillna(0)

cleaned_data = df.copy()

age_mean = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)

cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [43]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [44]:
df.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [45]:
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

# Cleaning Data 
## Handle Duplicate Values 
- duplicate()
- drop_duplicates()

In [46]:
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [47]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [48]:
df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [49]:
 df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [50]:
df[["country", "gender"]].duplicated()
df2 = df.copy()

#df.drop_duplicates(inplace=True)

## Handle Data Types and date-Time
- dtypes
- astypes(newtype)
- to_datetime()

In [51]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [52]:
df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [53]:
#changing the age datatype to int64

df2 = df.copy()
df2 = df2.fillna(0)

df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [54]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [55]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [56]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data

aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"])

aqi_data["timestamp"].dtype

dtype('<M8[ns]')

In [57]:
date_str = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

## Handle Strings
- .str.lower()
- .str.upper() & .capitalized()
- .str.strip()
- .str.split("")
- .str.contains(val, case=False)

In [58]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [59]:
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()

0        Male
1        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: object

In [60]:
df["name"].str.split(" ")  # for separating email on the basis of '@'

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [61]:
df["country"].str.contains("US")

df["country"].str.contains("india", case = False) #to ignore the case sensitive

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [62]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

# Transforming Data(Feature Engineering)
- apply()
- map()
- assign()
- replace(old, new)

In [63]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [64]:
df2 = df.copy()

In [71]:
df2["tax"] = df2["income"].apply(lambda x : "20%" if  x >= 50000 else "10%")  #apply() is the higher order function

df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [72]:
#map()

gender_map = {"Male":"M",
             "Female":"F",
             "Unknown":"U"}

df2["gender"] = df2["gender"].map(gender_map)

In [73]:
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  20%
1    1      John Doe  29.0     USA      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%

In [74]:
df2.assign(new_income = df2["income"] * 1.1)

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%     63800.0

In [84]:
df2["country"] = df2["country"].replace("US", "United States")
df2

    id          name   age        country gender   income  tax
0    1      John Doe  29.0  United States      M  55000.0  20%
1    1      John Doe  29.0  United States      M  55000.0  20%
2    2    Jane Smith   NaN         Canada      F  62000.0  20%
3    3          Alex   NaN  United States      U  47000.0  10%
4    4  Maria Garcia  34.0          Spain      F      NaN  10%
5    5        Li Wei  27.0          China      M  51000.0  20%
6    6           NaN  45.0          India      F  73000.0  20%
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%
8    8    Rachel Lee  29.0  United States      F  62000.0  20%
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%
10  10   Emily Davis  31.0  United States    NaN  58000.0  20%

# Transforming Data